name: Deploy Content to cwomsdemo [8502d4a1-7741-46a7-8f5b-1c12bd9a0009]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-8502d4a1-7741-46a7-8f5b-1c12bd9a0009.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-8502d4a1-7741-46a7-8f5b-1c12bd9a0009.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'cwomsdemorg'
      workspaceName: 'cwomsdemo'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_8502d4a1774146a78f5b1c12bd9a0009 }}
      contentTypes: 'Workbook'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_8502d4a1774146a78f5b1c12bd9a0009 }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      uses: juliangruber/sleep-action@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        time: 30s
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_8502d4a1774146a78f5b1c12bd9a0009 }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      uses: juliangruber/sleep-action@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      with:
        time: 30s
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_8502d4a1774146a78f5b1c12bd9a0009 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows/azure-sentinel-deploy.ps1'
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}